name: Build Spring boot (BackEnd)

on:
    push:
        branches: [ auto-deploy ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Build with DockerFile
          run: docker build -t spring-boot-backend:latest .
        - name: Log in To DOCKER HUB
          uses: docker/login-action@v3
          with:
            username: ${{secrets.DOCKER_HUB_USERNAME }}
            password: ${{secrets.DOCKERHUB_TOKEN}}
        - name: Push to DOCKER HUB
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: title20306/backend:v${{ github.run_number }}
        

            